Ability to get the last response
atymic/twitter pull request #359
Opened 2021-05-16 22:51 UTC by ejunker

Fixes #358 

Added a `getSyncClient()` method to `Querier` and added a `getResponse()` method to `SyncClient`. This allows you to access the last response including the headers.

I did not add anything to `AsyncClient` since I wasn't sure how that would work since it returns a Promise.
I wasn't sure the best way to update the tests so let me know if I should change anything. I wanted to test that the response is still set when there is an exception but couldn't figure out how to test that with the mocked objects.

2021-05-17 16:34 UTC, reliq requested changes
Looks good @ejunker, only a few suggestions.

Thank you for contributing 😄

2021-05-17 16:34 UTC, reliq commented on src/Contract/Http/SyncClient.php
> +    public function getResponse();
```suggestion
    public function getLastResponse();
```

2021-05-17 16:34 UTC, reliq commented on tests/Unit/Service/QuerierTest.php
> +        self::assertInstanceOf(SyncClient::class, $this->subject->getSyncClient());
We don't need this assertion since the method is a type-hinted getter.

```suggestion
```

2021-05-17 16:34 UTC, reliq commented on src/Contract/Querier.php
> +    public function getSyncClient(): SyncClient;
I'd also add `getAsyncClient()` for completeness sake.

2021-05-17 20:18 UTC, ejunker commented
@reliq  made the suggested changes. Renamed `getResponse()` to `getLastResponse()` and added `getAsyncClient()`

2021-05-17 20:20 UTC, reliq approved these changes

2021-05-18 00:36 UTC, atymic approved these changes

2021-05-18 00:36 UTC, merged

2021-05-18 00:37 UTC, atymic commented
Thanks for the PR @ejunker and thanks for the review @reliq  :)