Laravel 10
atymic/twitter pull request #408
Opened 2023-02-07 22:01 UTC by mustorze

2023-02-07 22:41 UTC, atymic requested changes
See suggestions

2023-02-07 22:41 UTC, atymic commented on composer.json
> +    "keywords": ["twitter", "laravel", "laravel5", "laravel6", "laravel7", "laravel8", "lareavel9", "laravel10"],
```suggestion
    "keywords": ["twitter", "laravel"],
```

2023-02-07 22:41 UTC, atymic commented on composer.json
> +        "php": "^8.1",
```suggestion
        "php": "^8.0",
```

2023-02-07 22:42 UTC, atymic requested changes

2023-02-07 22:42 UTC, atymic commented on composer.json
> +        "illuminate/support": "6 - 10",
```suggestion
        "illuminate/support": "^7.0 || ^8.0 || ^9.0 || ^10.0",
```

2023-02-14 17:00 UTC, mustorze commented
@atymic ✔

2023-02-15 10:30 UTC, dantaylorseo commented
When will this be merged please?

2023-02-15 10:57 UTC, atymic approved these changes

2023-02-15 10:57 UTC, merged